[package]
name = "rgb2yuv420"
version = "0.1.0"
authors = ["Marcell Bán <Marcell.Ban@ccsys.eu>"]
description = "Simple RGB to YUV420 converter"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
png = "0.12"